export const json ={
    make: {
      name: 'Lamborghini',
      niceName: 'lamborghini',
    },
    model: {
      id: 'Lamborghini_Urus',
      name: 'Urus',
      niceName: 'urus',
    },
    engine: {
      name: 'Gas',
      equipmentType: 'ENGINE',
      availability: 'STANDARD',
      compressionRatio: 9.7,
      cylinder: 8,
      size: 4,
      displacement: 3996,
      configuration: 'V',
      fuelType: 'premium unleaded (required)',
      horsepower: 641,
      torque: 627,
      totalValves: 32,
      type: 'gas',
      code: '8VTTG4.0',
      compressorType: 'twin turbocharger',
      rpm: {
        horsepower: 6000,
        torque: 2250,
      },
      valve: {
        timing: 'variable valve timing',
        gear: 'double overhead camshaft',
      },
    },
    transmission: {
      name: '8A',
      equipmentType: 'TRANSMISSION',
      availability: 'STANDARD',
      automaticType: 'Shiftable automatic',
      transmissionType: 'AUTOMATIC',
      numberOfSpeeds: '8',
    },
    drivenWheels: 'all wheel drive',
    numOfDoors: '4',
    options: [
      {
        category: 'Interior',
        options: [
          {
            id: '401785427',
            name: 'Bicolor Elegante Leather',
            description: 'Two-tone leather interior',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785444',
            name: 'Rear Seat Heating',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785463',
            name: 'Night Vision',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785426',
            name: 'Unicolor Sportivo Alcantara',
            description: 'Single-tone Alcantara interior',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785445',
            name: 'Rear Seat Entertainment',
            description: 'Two rear touch screen monitors with wireless audio/video streaming',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785436',
            name: 'Multifunctional Steering Wheel W/Suede Leather Inserts Heated',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785433',
            name: 'Floor Mats W/Leather Piping And Double Stitching',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785429',
            name: 'Bicolor Sportivo Alcantara',
            description: 'Two-tone Alcantara interior',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785428',
            name: 'Bicolor Sportivo Leather',
            description: 'Two-tone leather interior',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785434',
            name: 'Multifunctional Steering Wheel In Smooth Leather Heated',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785441',
            name: 'Contrast Stitching On Steering Wheel',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785447',
            name: 'Colored Seat Belt In Bianco Polar',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785456',
            name: 'Bang & Olufsen Advanced 3D Audio System',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785468',
            name: 'Cargo Management System',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785455',
            name: 'Insert In Wood-Open Pore W/Aluminum Insert',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785454',
            name: 'Insert In Wood-Open Pore',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785442',
            name: 'Full Electric Front Seats W/Ventilation And Massage',
            description:
              '18-way power adjustable front seats with power lumbar, heating, ventilation and massage functions; Electric steering wheel column',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785435',
            name: 'Multifunctional Steering Wheel W/Suede Leather Inserts',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785430',
            name: 'Q-citura W/Alcantara',
            description: 'Adds diamond pattern stitching on inner seat portions',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785457',
            name: 'Head Up Display (HUD)',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785443',
            name: '4 Seat Configuration W/Full Electric Front Seats',
            description:
              '4-seat configuration; Rear bucket seats with 8-way power adjustment and heating function',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785450',
            name: 'Colored Seat Belt In Terra Efire',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785449',
            name: 'Colored Seat Belt In Terra Asia',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785448',
            name: 'Colored Seat Belt In Rosso Rea',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785432',
            name: 'Optional Stitching',
            description: 'Contrast or inverted stitching',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785438',
            name: 'Multifunctional Steering Wheel W/Perforated Leather Inserts Heated',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785437',
            name: 'Multifunctional Steering Wheel W/Perforated Leather Inserts',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785439',
            name: 'Multifunctional Steering Wheel In Colored Leather',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785431',
            name: 'Q-citura W/Leather',
            description: 'Adds diamond pattern stitching on inner seat portions',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785453',
            name: 'Rear Center Console In Carbon',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785440',
            name: 'Multifunctional Steering Wheel In Colored Leather Heated',
            equipmentType: 'OPTION',
            availability: 'All',
          },
        ],
      },
      {
        category: 'Exterior',
        options: [
          {
            id: '401785417',
            name: 'Privacy Acoustic Double Glaze Glass',
            description:
              'Acoustic front side glass; Privacy double glazing on rear glass and rear window',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785286',
            name: 'Rims Asterope 21 Graphite Gray',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785287',
            name: 'Rims Nath 22 Silver',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785467',
            name: 'Tailgate Handless Opener',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785415',
            name: 'Black Roof Rails',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785423',
            name: 'Black Matt Exhaust Tailpipes',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785411',
            name: 'Green Painted Brake Calipers',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785288',
            name: 'Rims Nath 22 Titanium Matt',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785424',
            name: 'Bright Chrome Exhaust Tailpipes',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785416',
            name: 'Chrome Roof Rails',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785290',
            name: 'Rims Taigete 23 Shiny Black',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785418',
            name: 'Side Double Glaze And Heat Absorption Glass',
            description: 'All glass except third quarter glass',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785284',
            name: 'Rims Alcione 21 Titanium Matt',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785464',
            name: 'Wet-Arm Wiper W/Headlight Washer And RVC Cleaner',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785425',
            name: 'Manual Trailer Towing',
            description: 'Manual trailer hitch without tow ball',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785465',
            name: 'Heat Reflective Windscreen',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785285',
            name: 'Rims Asterope 21 Silver',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785291',
            name: 'Rims Taigete 23 Diamond Finished',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785289',
            name: 'Rims Nath 22 Diamond Finished',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785409',
            name: 'Orange Painted Brake Calipers',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785413',
            name: '21 Spare Wheel',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785466',
            name: 'Heat Reflective Windscreen W/Heating And Defrosting',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785412',
            name: '22 Pirelli PO Corsa Tire',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785283',
            name: 'Rims Alcione 21 Shiny Black',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785282',
            name: 'Black Painted Brake Caliper',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785408',
            name: 'Yellow Painted Brake Calipers',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785414',
            name: 'Electric Panorama Roof',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785410',
            name: 'Red Painted Brake Calipers',
            equipmentType: 'OPTION',
            availability: 'All',
          },
        ],
      },
      {
        category: 'Mechanical',
        options: [
          {
            id: '401785489',
            name: 'Fuel Tank 85 Liters',
            description: 'Higher capacity 22.5 gallon fuel tank',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785422',
            name: 'Offroad Modes W/Trailer Towing Preparation',
            description:
              'Steel skid plate with higher ramp angle on front and rear bumpers; Underfloor protection and reinforcement; Brushed steel exhaust pipes; Two additional driving modes for off-road conditions (TERRA, SABBIA)',
            equipmentType: 'OPTION',
            availability: 'All',
          },
        ],
      },
      {
        category: 'Additional Fees',
        options: [
          {
            id: '401785471',
            name: 'Maintenance Package 3 Years',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785470',
            name: 'Extension Of Warranty 5 Years',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785469',
            name: 'Extension Of Warranty 4 Years',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785472',
            name: 'Maintenance Package 5 Years',
            equipmentType: 'OPTION',
            availability: 'All',
          },
        ],
      },
      {
        category: 'Package',
        options: [
          {
            id: '401785446',
            name: 'Branding Pack',
            description: 'Embroidered',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785458',
            name: 'Ambient Light Package',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785420',
            name: 'Body Color Style Package',
            description: 'All exterior black matt parts in body color',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785462',
            name: 'Full ADAS Package W/Head Up Display',
            description: 'Advanced Driver Assistance Systems (ADAS)',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785452',
            name: 'Big Interior Carbon Package Front',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785421',
            name: 'Chrome Package',
            description: 'Chrome window covers',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785419',
            name: 'High Gloss Black Style Package',
            description: 'Black Matt exterior trim; High-gloss black painted grilles',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785451',
            name: 'Small Interior Carbon Package Front',
            equipmentType: 'OPTION',
            availability: 'All',
          },
        ],
      },
      {
        category: 'Safety',
        options: [
          {
            id: '401785459',
            name: 'Highway Assistant Package',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785461',
            name: 'Top View Camera',
            equipmentType: 'OPTION',
            availability: 'All',
          },
          {
            id: '401785460',
            name: 'Urban Road Assistant Package',
            equipmentType: 'OPTION',
            availability: 'All',
          },
        ],
      },
    ],
    colors: [
      {
        category: 'Interior',
        options: [
          {
            id: '401786232',
            name: 'Nero Ade/Bianco Leda Sportivo Alcantara',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785582',
            name: 'Terra Asia Vintage Elegante Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401786233',
            name: 'Nero Ade/Verde Faunus Sportivo Alcantara',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401786231',
            name: 'Nero Ade/Giallo Taurus Sportivo Alcantara',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785576',
            name: 'Nero Ade/Bianco Leda Sportivo Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785578',
            name: 'Nero Ade/Rosso Alala Sportivo Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785572',
            name: 'Marrone Elpis Unicolor Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785586',
            name: 'Grigio Octans Unicolor Alcantara',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785584',
            name: 'Blu Teia Vintage Elegante Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401786234',
            name: 'Nero Ade/Rosso Alala Sportivo Alcantara',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401786230',
            name: 'Nero Ade/Arancio Leonis Sportivo Alcantara',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785579',
            name: 'Nero Ade/Verde Faunus Sportivo Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785575',
            name: 'Nero Ade/Arancio Leonis Sportivo Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785577',
            name: 'Nero Ade/Blu Amon Sportivo Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785573',
            name: 'Grogio Octans Unicolor Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785571',
            name: 'Nero Ade Unicolor Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785585',
            name: 'Nero Ade Unicolor Alcantara',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785581',
            name: 'Rosso Rea Elegante Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785574',
            name: 'Nero Ade/Giallo Taurus Sportivo Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785580',
            name: 'Bianco Polar Elegante Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785583',
            name: 'Terra Efire Vintage Elegante Leather',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
        ],
      },
      {
        category: 'Exterior',
        options: [
          {
            id: '401785266',
            name: 'Nero Noctis',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785275',
            name: 'Blu Astraeus Metallic',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785276',
            name: 'Blu Eleos Metallic',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785271',
            name: 'Rosso Mars Metallic',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785277',
            name: 'Verde Hebe Metallic',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785273',
            name: 'Bianco Icarus Metallic',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785274',
            name: 'Giallo Auge',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785272',
            name: 'Marrone Alcestis Metallic',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785278',
            name: 'Rosso Anteros Metallic',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785268',
            name: 'Bianco Monocerus',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785269',
            name: 'Grigio Nimbus Metallic',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785270',
            name: 'Grigio Lynx Metallic',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
          {
            id: '401785267',
            name: 'Nero Helene Metallic',
            equipmentType: 'COLOR',
            availability: 'USED',
          },
        ],
      },
    ],
    price: {
      baseMsrp: 200000,
      deliveryCharges: 3995,
      estimateTmv: false,
    },
    categories: {
      primaryBodyType: 'SUV',
      market: 'High-Performance,Crossover,Exotic',
      crossover: 'Car',
      epaClass: 'Standard Sport Utility Vehicles',
      vehicleSize: 'Large',
      vehicleType: 'SUV',
      vehicleStyle: '4dr SUV',
    },
    squishVin: 'ZPBUA1ZLKL',
    years: [
      {
        id: 401784259,
        year: 2019,
        styles: [
          {
            id: 401784260,
            name: '4dr SUV AWD (4.0L 8cyl Turbo 8A)',
            submodel: {
              body: 'SUV',
              modelName: 'Urus SUV',
              niceName: 'suv',
            },
            trim: 'Base',
          },
        ],
      },
    ],
    matchingType: 'SQUISHVIN',
    mpg: {
      highway: '17',
      city: '12',
    },
  } 